### ISSUE TITLE
fileExists or pathExists

### ISSUE THREAD

**Issue by lovettchris** [leanprover/std4#1]
This is ugly, a friendly wrapper in the same namespace as `IO.FS.readFile` would be nice.  Something like this:

```lean

def fileExists (p : FilePath) : BaseIO Bool :=
  return (← p.metadata.toBaseIO).toBool

```

**Comment by JamesGallicchio** [comment]
+1, I didn't know there was even a way to get that information :)

**Comment by Kha** [comment]
[`System.FilePath.pathExists`](https://leanprover-community.github.io/mathlib4_docs/Init/System/IO.html#System.FilePath.pathExists)
