### ISSUE TITLE
After import Std, the behavior of HMod.hMod of Int changed without warning.

### ISSUE THREAD

**Issue by JiechengZhao** [leanprover/std4#411]
It appears to be a feature introduced in https://github.com/leanprover/std4/pull/64. However, this is quite unexpected. Normally, we do not expect importing a library to result in a change to the built-in behavior or at least some warning may be raised.

@semorrison @digama0

``` lean
example : -1 / 3 = 0 := by decide  -- Int.div here
```

or 
``` lean 
import Std 
example : -1 / 3 = -1 := by decide  -- Int.ediv here
```

Versions
"4.3.0-rc2"
Ubuntu 22.04.3 LTS

**Comment by digama0** [comment]
This is a "temporary workaround" for undesirable behavior in core to be fixed eventually, see https://leanprover.zulipchat.com/#narrow/stream/341532-lean4-dev/topic/.5BRFC.5D.20Int.2Ediv.20convention/near/376803279 and the surrounding topic. This workaround can be removed from Std when it is fixed upstream, but for now it is probably best to pretend the upstream impl doesn't exist.

**Comment by JiechengZhao** [comment]
> This is a "temporary workaround" for undesirable behavior in core to be fixed eventually, see https://leanprover.zulipchat.com/#narrow/stream/341532-lean4-dev/topic/.5BRFC.5D.20Int.2Ediv.20convention/near/376803279 and the surrounding topic. This workaround can be removed from Std when it is fixed upstream, but for now it is probably best to pretend the upstream impl doesn't exist.

So I shall use `Int.div` instead of `/` when I need a rounding down div. Is it right?

**Comment by digama0** [comment]
`Int.ediv` rounds down. If you mean round-to-zero then yes you should use `Int.div`.

**Comment by JiechengZhao** [comment]
> `Int.ediv` rounds down. If you mean round-to-zero then yes you should use `Int.div`. (But also you should report your example on the Zulip thread, we are interested to hear use cases for `Int.div`)

Now I understand the story. Thank you for your help.
