### ISSUE TITLE
Int.ofNat_natAbs_eq_of_nonneg and Int.natAbs_of_nonneg seem duplicates

### ISSUE THREAD

**Issue by Ruben-VandeVelde** [leanprover/std4#419]

**Comment by digama0** [comment]
A quick search in mathlib suggests `ofNat_natAbs_eq_of_nonneg` is used 4 times and `natAbs_of_nonneg` is used 30 times. I'm fine keeping only the shorter name and deprecating the other one. Other opinions?

**Comment by semorrison** [comment]
LGTM.
