### ISSUE TITLE
Usage examples for HashMap.lean

### ISSUE THREAD

**Issue by digama0** [leanprover/std4#469]
Currently the HashMap docs have no code examples. We should have examples similar to those from `Std.Data.List.Basic`:
````lean
/--
Split a list at every occurrence of a separator element. The separators are not in the result.
```
[1, 1, 2, 3, 2, 4, 4].splitOn 2 = [[1, 1], [3], [4, 4]]
```
-/
@[inline] def splitOn [BEq α] (a : α) (as : List α) : List (List α) := as.splitOnP (· == a)
````

**Comment by austinletson** [comment]
@digama0 are there other files needing examples or general documentation?

**Comment by digama0** [comment]
Most of them are in lean core: `Init.Data.List.BasicAux`, `Init.Data.List.Control`, `Init.Data.Fin.Basic`, `Init.Data.String.Basic`, `Init.Data.Array.Basic` all contain many functions which should have documentation at around the same level as `Init.Data.List.Basic` or `Std.Data.List.Basic`. Std has had mandatory documentation from the beginning so it's not hurting quite as much for docs.
