### ISSUE TITLE
`omega` has issues with `mdata` handling

### ISSUE THREAD

**Issue by girving** [leanprover/std4#509]
This MWE is [from Damiano Testa](https://leanprover.zulipchat.com/#narrow/stream/239415-metaprogramming-.2F-tactics/topic/A.20simple.20result.20that.20.60omega.60.20fails.20to.20prove/near/410999690), and I've hit it in the wild in [other cases](https://leanprover.zulipchat.com/#narrow/stream/239415-metaprogramming-.2F-tactics/topic/A.20simple.20result.20that.20.60omega.60.20fails.20to.20prove/near/411264731):

```
import Std.Tactic.Omega

example : 0 = 0 := by
  have : 0 = 0 := by omega -- works
  omega -- fails
```

He suggests it's `mdata`-related, and indeed a [tactic he wrote that clears `mdata`](https://leanprover.zulipchat.com/#narrow/stream/239415-metaprogramming-.2F-tactics/topic/A.20simple.20result.20that.20.60omega.60.20fails.20to.20prove/near/411009284) fixes the problem.

**Comment by dwrensha** [comment]
Looks like this issue can be closed. #510 has been merged, and the example works now.
