### ISSUE TITLE
Installation instruction confusion

### ISSUE THREAD

**Issue by mars0i** [leanprover/std4#689]
Hi,

I'm a Lean newbie, and I'm trying to use std4 (or at least find out what's in it--I haven't found any online docs).  I'm having trouble following some parts of the README.md here in github.  I'm wondering if it would be helpful to modify the README to make it easier for people like me (or whether there is some other source I should read first--haven't found it yet!).

I understand what this says and I have implemented it:
> To use std4 in your project, add the following to your lakefile.lean:
> require std from git "https://github.com/leanprover/std4" @ "main"

What does that do?  After I examine a source file from a directory containing such a lakefile.lean, is std4 installed on my system? Where is it?  

Where do I need to be to implement the instructions in the README.md in order to generate std4's docs?  Not in my own source directory--I tried that, and I didn't expect it to work.  So I cloned the repo, and I can run these commands in its directory.  Is that what I was supposed to do?  Or did putting the `require` line in my lakefile.lean install the std4 source somewhere, and should build the docs there?

(This isn't your issue, but I'm also wondering whether I can configure LSP to provide documentation on functions and data structures from within an editor.)

Thanks!

**Comment by digama0** [comment]
For introductory questions such as this, we generally advise the use of the zulip chat https://leanprover.zulipchat.com/ . Please re-open an issue once this is narrowed to specific changes to the readme or similar.

**Comment by mars0i** [comment]
Thanks @digama0.  I'll ask there.  I thought about asking on Zulip first, but thought that maybe it would be worth suggesting a small documentation change.  When you're starting out with a language, it's hard to know what should be considered mere ignorance about what everybody knows. :-)

**Comment by mars0i** [comment]
OK--I understand.  Thanks.
