### ISSUE TITLE
`List.pmap`, but for proofs only and O(1)

### ISSUE THREAD

**Issue by digama0** [leanprover/std4#711]
I think there is currently an API hole between `List.attach`, which produces `List {x // x \in l}` but is a compiler no-op, and `List.pmap`, which produces `List B` from an arbitrary partial mapping function but is equivalent to `List.map` at run time (and hence is linear time). If we want to produce `List {x // P x}` for some `P` which is not just `fun x => x \in l`, we have to use `pmap` and lose the O(1) behavior.

Proposal:
```lean
/-- O(1) by compiler magic -/
def attachWith (l : List α) (P : α → Prop) (H : ∀ x ∈ l, P x) : List {x // P x} := l.pmap Subtype.mk H
```
Any better naming ideas?

**Comment by semorrison** [comment]
Name seems good. Could you give an example of another interesting `P` you have in mind?
