### ISSUE TITLE
Do not make `#guard_msgs` sensitive to whitespace and line breaks

### ISSUE THREAD

**Issue by Seasawher** [leanprover/std4#717]
Thanks for the great library. This is a request for an additional feature. 

In the following example, there is an unnatural space between `instance` and `Inv α`, but an error will occur if there is not a space of exactly this length. This behaviour of `#guard_msgs` is inconvenient and should ignore spaces and newlines.

```lean
import Mathlib.Tactic

variable (α : Type)

/--
error: failed to synthesize instance   Inv α
-/
#guard_msgs in
#check (_ : α)⁻¹
```

Thank you for reading.

**Comment by digama0** [comment]
`#guard_msgs` is upstream now, you should reopen the issue on lean4 repo. That said, this is a deliberate behavior, which is meant to catch errors in whitespace handling by tactics (this has caught bugs). The code action should help you produce a correctly structured doc comment.

**Comment by Seasawher** [comment]
Thanks for the reply. I now understand why `#guard_msgs` is designed the way it is today.

On the other hand, I'm not happy with it. I want a command that does the same thing as `#guard_msgs`, but is not sensitive to whitespace.

I will open an issue again in the Lean4 repo. Thanks.

**Comment by digama0** [comment]
On the linked issue, there did appear to be [some appetite](https://github.com/leanprover/lean4/issues/3571#issuecomment-1979893142) for having this as a `#guard_msgs` option, but it seemed not to be sufficiently motivated to be worth investigation (and it was also mixed up with some other related normalizations people may want). If you want to pursue this I suggest you open it as an issue upstream and lay out your use cases.
